backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "AltText", name: "altText", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Publish Date", name: "date", widget: "datetime"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

  - name: "patterns"
    label: "Patterns"
    folder: "src/pages/patterns"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "pattern-item"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Published", name: "date", widget: "datetime"}
      - {label: "Original Publication", name: "originalPub", widget: "string"}
      - {label: "Current Source", name: "currentSrc", widget: "string", required: false}
      - {label: "Item Type", name: "itemType", widget: "string"}
      - {label: "Yarn(s)", name: "yarn", widget: "list"}
      - {label: "Yarn Weight", name: "yarnWeight", widget: "list"}
      - label: "Yardage"
        name: "yardage"
        widget: "list"
        fields:
          - {label: "Variant", name: "variant", widget: "string", required: false}
          - {label: "Yards", name: "yards", widget: "string"}
          - {label: "Meters", name: "meters", widget: "string"}
      - {label: "Gauge", name: "gauge", widget: "list"}
      - {label: "Needles", name: "needles", widget: "string"}
      - {label: "Sizes", name: "sizes", widget: "string"}
      - label: "Finished Measurements"
        name: "finalMeasure"
        widget: "list"
        fields:
          - {label: "Dimension Name", name: "dimName", widget: "string"}
          - {label: "Inches", name: "inches", widget: "string"}
          - {label: "Centimeters", name: "cm", widget: "string"}
      - label: "Pattern Source"
        name: "patternSource"
        widget: "object"
        fields:
          - {label: "Link", name: "link", widget: "string"}
          - {label: "Price", name: "price", widget: "number", pattern: [^\d+(,\d{2})?$, "must be a valid numeric price with two decimal places"]}
      - {label: "Pattern Image", name: "pattImage", widget: "image"}
      - {label: "Pattern Alt Text", name: "pattAltText", widget: "string"}
      - {label: "Top Image", name: "topImage", widget: "image"}
      - label: "Pictures"
        name: "pictures"
        widget: "list"
        fields:
          - {label: "Photo", name: "photo", widget: "image"}
          - {label: "Alt Text", name: "altText", widget: "string"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}